import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, PackageCheck } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../services/api';
import type { PurchaseOrder } from '../../types';

const receiveSchema = z.object({ items: z.array(z.object({ materialId: z.string(), quantity: z.coerce.number().min(0, 'Quantity cannot be negative.') })) });
type ReceiveValues = z.infer<typeof receiveSchema>;
type ReceiveInput = z.input<typeof receiveSchema>;

export function PurchaseOrderDetailPage() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { user } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ['purchase-order', id], enabled: Boolean(id), queryFn: async () => { const response = await api.get<PurchaseOrder & { projectId?: PurchaseOrder['project']; supplierId?: PurchaseOrder['supplier'] }>(`/purchase-orders/${id}`); const order = response.data; if (!order) throw new Error('Purchase order response was empty.'); return { ...order, project: order.project || order.projectId, supplier: order.supplier || order.supplierId, items: order.items.map((item) => ({ ...item, material: item.material || (item as typeof item & { materialId?: typeof item.material }).materialId })) } as PurchaseOrder; } });
  const receive = useMutation({ mutationFn: (values: ReceiveValues) => api.post(`/purchase-orders/${id}/receive`, values), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['purchase-order', id] }); await client.invalidateQueries({ queryKey: ['inventory'] }); }, onError: () => undefined });
  const canReceive = user && ['admin', 'manager', 'store_keeper'].includes(user.role);
  if (query.isLoading) return <State text="Loading purchase order..." />;
  if (query.isError || !query.data) return <State text={query.error instanceof Error ? query.error.message : 'Purchase order not found.'} error />;
  const order = query.data;
  return <div className="space-y-6"><button type="button" onClick={() => navigate('/purchase-orders')} className="flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-amber-300"><ArrowLeft size={15} /> Back to purchase orders</button><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span className="font-mono text-xs font-bold text-amber-400">{order.poNumber}</span><h1 className="mt-2 text-2xl font-black font-heading text-white">Purchase order detail</h1><p className="mt-1 text-xs text-slate-400">Review ordered quantities and record received goods.</p></div><StatusBadge status={order.status} size="md" /></div><section className="grid gap-4 sm:grid-cols-3"><Info label="Project" value={typeof order.project === 'string' ? order.project : order.project.name} /><Info label="Supplier" value={typeof order.supplier === 'string' ? order.supplier : order.supplier.name} /><Info label="Total amount" value={order.totalAmount.toLocaleString()} /></section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 text-sm font-bold text-white">Ordered items</h2><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Material</th><th className="px-4 py-3">Ordered</th><th className="px-4 py-3">Received</th><th className="px-4 py-3">Remaining</th></tr></thead><tbody className="divide-y divide-slate-800/70">{order.items.map((item) => <tr key={item._id || String(item.material)}><td className="px-4 py-4 text-white">{typeof item.material === 'string' ? item.material : item.material.name}</td><td className="px-4 py-4 text-slate-300">{item.quantity}</td><td className="px-4 py-4 text-slate-300">{item.receivedQuantity || 0}</td><td className="px-4 py-4 font-semibold text-amber-300">{item.quantity - (item.receivedQuantity || 0)}</td></tr>)}</tbody></table></div></section>{canReceive && order.status !== 'received' && order.status !== 'cancelled' && <ReceiveForm order={order} submitting={receive.isPending} onSubmit={(values) => receive.mutate(values)} />}</div>;
}
function ReceiveForm({ order, submitting, onSubmit }: { order: PurchaseOrder; submitting: boolean; onSubmit: (values: ReceiveValues) => void }) { const { register, handleSubmit } = useForm<ReceiveInput, unknown, ReceiveValues>({ resolver: zodResolver(receiveSchema), defaultValues: { items: order.items.map((item) => ({ materialId: typeof item.material === 'string' ? item.material : item.material._id, quantity: 0 })) } }); return <form onSubmit={handleSubmit(onSubmit)} className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="mb-4 flex items-center gap-2"><PackageCheck size={18} className="text-amber-300" /><h2 className="text-sm font-bold text-white">Receive goods</h2></div>{order.items.map((item, index) => <div className="mb-3 grid gap-2 sm:grid-cols-[1fr_160px]" key={item._id || index}><p className="rounded-lg border border-slate-800 bg-slate-950/40 px-3 py-2 text-xs text-slate-300">{typeof item.material === 'string' ? item.material : item.material.name}</p><input {...register(`items.${index}.quantity`)} type="number" min="0" max={item.quantity - (item.receivedQuantity || 0)} className="form-input" placeholder="Batch quantity" /></div>)}<button type="submit" disabled={submitting} className="mt-2 rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-bold text-slate-950 disabled:opacity-50">{submitting ? 'Receiving...' : 'Record goods receipt'}</button></form>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-white">{value}</p></div>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-xl border p-8 text-center text-sm ${error ? 'border-rose-900/60 bg-rose-950/30 text-rose-300' : 'border-dashed border-slate-700 bg-slate-900/40 text-slate-400'}`}>{text}</div>; }
