import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Modal } from '../../components/common/Modal';
import { useAuth } from '../../context/AuthContext';
import { useProject } from '../../context/ProjectContext';
import { api } from '../../services/api';
import type { Material, WasteReason, WasteRecord } from '../../types';

const reasons: WasteReason[] = ['damaged', 'expired', 'spillage', 'defective', 'overuse', 'natural_loss', 'other'];
const wasteSchema = z.object({ materialId: z.string().min(1, 'Material is required.'), projectId: z.string().min(1, 'Project is required.'), quantity: z.coerce.number().min(1, 'Quantity must be at least 1.'), reason: z.enum(reasons), description: z.string().optional(), date: z.string().optional() });
type WasteValues = z.infer<typeof wasteSchema>;
type WasteInput = z.input<typeof wasteSchema>;

async function getRecords() { const response = await api.get<WasteRecord[]>('/waste', { limit: 100 }); const rows = Array.isArray(response.data) ? response.data : (response.data as unknown as { wasteRecords?: WasteRecord[] }).wasteRecords || []; return rows.map((record) => { const raw = record as WasteRecord & { materialId?: WasteRecord['material']; projectId?: WasteRecord['project']; date?: string }; return { ...raw, material: raw.material || raw.materialId || 'Unknown material', project: raw.project || raw.projectId || 'Unknown project', incidentDate: raw.incidentDate || raw.date || '' }; }); }
async function getMaterials() { const response = await api.get<Material[]>('/materials', { isActive: true, limit: 100 }); return Array.isArray(response.data) ? response.data : (response.data as unknown as { materials?: Material[] }).materials || []; }

export function WastePage() {
  const { user } = useAuth();
  const { projects } = useProject();
  const client = useQueryClient();
  const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const records = useQuery({ queryKey: ['waste'], queryFn: getRecords });
  const materials = useQuery({ queryKey: ['materials', 'waste'], queryFn: getMaterials });
  const create = useMutation({ mutationFn: (values: WasteValues) => api.post('/waste', values), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['waste'] }); setOpen(false); }, onError: (cause) => setError(cause instanceof Error ? cause.message : 'Unable to record waste.') });
  const canCreate = user && ['admin', 'manager', 'engineer', 'store_keeper'].includes(user.role);
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-rose-400"><Trash2 size={20} /><span className="eyebrow">LOSS CONTROL</span></div><h1 className="mt-2 text-2xl font-black font-heading text-white">Waste Management</h1><p className="mt-1 text-xs text-slate-400">Record and review material loss with backend-calculated cost impact.</p></div>{canCreate && <button type="button" onClick={() => { setError(null); setOpen(true); }} className="flex items-center gap-2 rounded-xl bg-rose-500 px-4 py-2.5 text-xs font-bold text-white hover:bg-rose-400"><Plus size={16} /> Log waste incident</button>}</div>{records.isLoading && <State text="Loading waste records..." />}{records.isError && <State text={records.error instanceof Error ? records.error.message : 'Unable to load waste records.'} error />}{records.isSuccess && !records.data.length && <State text="No waste incidents have been recorded." />}{records.data && records.data.length > 0 && <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Material</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3">Quantity</th><th className="px-4 py-3">Cost impact</th><th className="px-4 py-3">Description</th></tr></thead><tbody className="divide-y divide-slate-800/70">{records.data.map((record) => <tr key={record._id}><td className="px-4 py-4 text-slate-400">{record.incidentDate}</td><td className="px-4 py-4 text-white">{typeof record.material === 'string' ? record.material : record.material.name}</td><td className="px-4 py-4 text-slate-300">{typeof record.project === 'string' ? record.project : record.project.name}</td><td className="px-4 py-4 capitalize text-rose-300">{record.reason.replaceAll('_', ' ')}</td><td className="px-4 py-4 text-slate-300">{record.quantity} {typeof record.material === 'string' ? '' : record.material.unit}</td><td className="px-4 py-4 font-semibold text-rose-300">{record.costImpact.toLocaleString()}</td><td className="max-w-xs px-4 py-4 text-slate-500">{record.description || '—'}</td></tr>)}</tbody></table></div>}{error && <p className="text-xs text-rose-300" role="alert">{error}</p>}<Modal isOpen={open} onClose={() => setOpen(false)} title="Log waste incident"><WasteForm projects={projects} materials={materials.data || []} submitting={create.isPending} onSubmit={(values) => create.mutate(values)} /></Modal></div>;
}
function WasteForm({ projects, materials, submitting, onSubmit }: { projects: Array<{ _id: string; code: string; name: string }>; materials: Material[]; submitting: boolean; onSubmit: (values: WasteValues) => void }) { const { register, handleSubmit, formState: { errors } } = useForm<WasteInput, unknown, WasteValues>({ resolver: zodResolver(wasteSchema), defaultValues: { projectId: '', materialId: '', quantity: 1, reason: 'damaged', description: '', date: '' } }); return <form onSubmit={handleSubmit(onSubmit)} className="space-y-4"><Field label="Project" error={errors.projectId?.message}><select {...register('projectId')} className="form-input"><option value="">Select project</option>{projects.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Material" error={errors.materialId?.message}><select {...register('materialId')} className="form-input"><option value="">Select material</option>{materials.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Quantity" error={errors.quantity?.message}><input {...register('quantity')} type="number" min="1" className="form-input" /></Field><Field label="Reason" error={errors.reason?.message}><select {...register('reason')} className="form-input">{reasons.map((reason) => <option key={reason} value={reason}>{reason.replaceAll('_', ' ')}</option>)}</select></Field><Field label="Incident date" error={errors.date?.message}><input {...register('date')} type="date" className="form-input" /></Field></div><Field label="Description" error={errors.description?.message}><textarea {...register('description')} rows={3} className="form-input" /></Field><button type="submit" disabled={submitting} className="w-full rounded-xl bg-rose-500 px-4 py-3 text-xs font-bold text-white hover:bg-rose-400 disabled:opacity-50">{submitting ? 'Recording...' : 'Record waste incident'}</button></form>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-xs font-semibold text-slate-300">{label}<div className="mt-1">{children}</div>{error && <span className="mt-1 block text-[11px] font-normal text-rose-300">{error}</span>}</label>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-xl border p-8 text-center text-sm ${error ? 'border-rose-900/60 bg-rose-950/30 text-rose-300' : 'border-dashed border-slate-700 bg-slate-900/40 text-slate-400'}`}>{text}</div>; }
