import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownToLine, ArrowUpFromLine, History, Warehouse } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Modal } from '../../components/common/Modal';
import { useProject } from '../../context/ProjectContext';
import { api } from '../../services/api';
import type { InventoryItem, InventoryTransaction, Material } from '../../types';

const movementSchema = z.object({ materialId: z.string().min(1, 'Material is required.'), projectId: z.string().min(1, 'Project is required.'), quantity: z.coerce.number().min(1, 'Quantity must be at least 1.'), notes: z.string().optional() });
type MovementValues = z.infer<typeof movementSchema>;
type MovementInput = z.input<typeof movementSchema>;

async function getPayload<T>(endpoint: string, params?: Record<string, string | boolean>) {
  const response = await api.get<T>(endpoint, params);
  if (Array.isArray(response.data)) return response.data as T;
  if (endpoint.includes('transactions')) {
    const rows = response.data as T;
    return (rows as InventoryTransaction[]).map((row) => ({ ...row, material: (row as InventoryTransaction & { materialId?: InventoryTransaction['material'] }).material || (row as InventoryTransaction & { materialId?: InventoryTransaction['material'] }).materialId })) as T;
  }
  const rows = response.data as T;
  return (rows as InventoryItem[]).map((item) => { const raw = item as InventoryItem & { materialId?: InventoryItem['material']; projectId?: InventoryItem['project'] }; return { ...raw, material: raw.material || raw.materialId, project: raw.project || raw.projectId }; }) as T;
}

export function InventoryPage() {
  const { projects } = useProject();
  const client = useQueryClient();
  const [tab, setTab] = useState<'stock' | 'transactions'>('stock');
  const [lowStock, setLowStock] = useState(false);
  const [movement, setMovement] = useState<'issue' | 'return' | null>(null);
  const [movementError, setMovementError] = useState<string | null>(null);
  const inventory = useQuery({ queryKey: ['inventory', lowStock], queryFn: () => getPayload<InventoryItem[]>('/inventory', { lowStock }) });
  const transactions = useQuery({ queryKey: ['inventory-transactions'], queryFn: () => getPayload<InventoryTransaction[]>('/inventory/transactions') });
  const materials = useQuery({ queryKey: ['materials', 'inventory'], queryFn: () => getPayload<Material[]>('/materials', { isActive: true }) });
  const action = useMutation({ mutationFn: ({ type, values }: { type: 'issue' | 'return'; values: MovementValues }) => api.post(`/inventory/${type}`, values), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['inventory'] }); await client.invalidateQueries({ queryKey: ['inventory-transactions'] }); setMovement(null); setMovementError(null); }, onError: (cause) => setMovementError(cause instanceof Error ? cause.message : 'Unable to complete this movement.') });
  return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-amber-500"><Warehouse size={20} /><span className="eyebrow">STOCK CONTROL</span></div><h1 className="mt-2 text-2xl font-black font-heading text-white">Inventory Ledger</h1><p className="mt-1 text-xs text-slate-400">Review current stock and trace every material movement.</p></div><div className="flex gap-2">{tab === 'stock' && <><button type="button" onClick={() => { setMovementError(null); setMovement('issue'); }} className="flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-amber-500"><ArrowUpFromLine size={15} /> Issue</button><button type="button" onClick={() => { setMovementError(null); setMovement('return'); }} className="flex items-center gap-2 rounded-xl bg-amber-500 px-3 py-2 text-xs font-bold text-slate-950 hover:bg-amber-400"><ArrowDownToLine size={15} /> Return</button></>}</div></div><div className="flex gap-2 border-b border-slate-800"><button type="button" onClick={() => setTab('stock')} className={`border-b-2 px-3 py-3 text-xs font-bold ${tab === 'stock' ? 'border-amber-500 text-amber-300' : 'border-transparent text-slate-400'}`}>Current stock</button><button type="button" onClick={() => setTab('transactions')} className={`flex items-center gap-2 border-b-2 px-3 py-3 text-xs font-bold ${tab === 'transactions' ? 'border-amber-500 text-amber-300' : 'border-transparent text-slate-400'}`}><History size={14} /> Transactions</button></div>{tab === 'stock' ? <><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={lowStock} onChange={(event) => setLowStock(event.target.checked)} className="accent-amber-500" /> Low stock only</label><StockTable query={inventory} /></> : <TransactionTable query={transactions} />}{movement && <Modal isOpen onClose={() => { setMovement(null); setMovementError(null); }} title={movement === 'issue' ? 'Issue material' : 'Return material'}><MovementForm type={movement} projects={projects} materials={materials.data || []} submitting={action.isPending} error={movementError} onSubmit={(values) => action.mutate({ type: movement, values })} /></Modal>}</div>;
}

function StockTable({ query }: { query: ReturnType<typeof useQuery<InventoryItem[]>> }) { const rows = query.data || []; if (query.isLoading) return <State text="Loading inventory..." />; if (query.isError) return <State text="Unable to load inventory." error />; if (!rows.length) return <State text="No inventory records match this filter." />; return <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[700px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Material</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Current stock</th><th className="px-4 py-3">Reorder level</th><th className="px-4 py-3">Updated</th></tr></thead><tbody className="divide-y divide-slate-800/70">{rows.map((item) => <tr key={item._id}><td className="px-4 py-4 font-semibold text-white">{typeof item.material === 'string' ? item.material : (item.material ? `${item.material.code} · ${item.material.name}` : 'Unknown')}</td><td className="px-4 py-4 text-slate-300">{typeof item.project === 'string' ? item.project : (item.project ? item.project.name : 'Unknown')}</td><td className={`px-4 py-4 font-bold ${item.material && item.currentStock <= item.material.reorderLevel ? 'text-rose-300' : 'text-emerald-300'}`}>{item.currentStock} {item.material?.unit || ''}</td><td className="px-4 py-4 text-slate-400">{item.material?.reorderLevel || '—'}</td><td className="px-4 py-4 text-slate-500">{item.lastUpdated || '—'}</td></tr>)}</tbody></table></div>; }
function TransactionTable({ query }: { query: ReturnType<typeof useQuery<InventoryTransaction[]>> }) { const rows = query.data || []; if (query.isLoading) return <State text="Loading transactions..." />; if (query.isError) return <State text="Unable to load transactions." error />; if (!rows.length) return <State text="No inventory movements recorded." />; return <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Material</th><th className="px-4 py-3">Quantity</th><th className="px-4 py-3">Balance after</th><th className="px-4 py-3">Notes</th></tr></thead><tbody className="divide-y divide-slate-800/70">{rows.map((row) => <tr key={row._id}><td className="px-4 py-4 text-slate-400">{row.createdAt}</td><td className="px-4 py-4 font-bold text-amber-300">{row.type}</td><td className="px-4 py-4 text-slate-300">{typeof row.material === 'string' ? row.material : row.material.name}</td><td className="px-4 py-4 text-white">{row.quantity}</td><td className="px-4 py-4 text-emerald-300">{row.balanceAfter}</td><td className="px-4 py-4 text-slate-500">{row.notes || '—'}</td></tr>)}</tbody></table></div>; }
function MovementForm({ type, projects, materials, submitting, error, onSubmit }: { type: 'issue' | 'return'; projects: Array<{ _id: string; code: string; name: string }>; materials: Material[]; submitting: boolean; error: string | null; onSubmit: (values: MovementValues) => void }) { const { register, handleSubmit, formState: { errors } } = useForm<MovementInput, unknown, MovementValues>({ resolver: zodResolver(movementSchema), defaultValues: { materialId: '', projectId: '', quantity: 1, notes: '' } }); return <form onSubmit={handleSubmit(onSubmit)} className="space-y-4"><Field label="Project" error={errors.projectId?.message}><select {...register('projectId')} className="form-input"><option value="">Select project</option>{projects.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Material" error={errors.materialId?.message}><select {...register('materialId')} className="form-input"><option value="">Select material</option>{materials.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Quantity" error={errors.quantity?.message}><input {...register('quantity')} type="number" min="1" className="form-input" /></Field><Field label="Notes" error={errors.notes?.message}><textarea {...register('notes')} rows={3} className="form-input" /></Field>{error && <p className="text-xs text-rose-300" role="alert">{error}</p>}<button type="submit" disabled={submitting} className="w-full rounded-xl bg-amber-500 px-4 py-3 text-xs font-bold text-slate-950 disabled:opacity-50">{submitting ? 'Saving...' : type === 'issue' ? 'Issue material' : 'Return material'}</button></form>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-xs font-semibold text-slate-300">{label}<div className="mt-1">{children}</div>{error && <span className="mt-1 block text-[11px] font-normal text-rose-300">{error}</span>}</label>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-xl border p-8 text-center text-sm ${error ? 'border-rose-900/60 bg-rose-950/30 text-rose-300' : 'border-dashed border-slate-700 bg-slate-900/40 text-slate-400'}`}>{text}</div>; }
