import { useQuery } from '@tanstack/react-query';
import { BarChart3 } from 'lucide-react';
import { useState } from 'react';
import { useProject } from '../../context/ProjectContext';
import { api } from '../../services/api';

type Tab = 'cost' | 'abc' | 'sde' | 'eoq';
interface CostData { summary: { totalOrdered: number; totalOrderedCost: number; totalIssued: number; totalWaste: number; totalWasteCost: number; wastePercentage: number }; byCategory: Array<{ category: string; quantity: number; cost: number }> }
interface ABCItem { materialId: string; materialName: string; annualConsumptionValue: number; percentage: number; classification: string }
interface SDEItem { materialId: string; materialName: string; scarcity: string; difficulty: string; classification: string }
interface EOQItem { materialId: string; materialName: string; annualDemand: number; orderingCost: number; holdingCost: number; eoq: number; totalCost: number }

export function AnalyticsPage() {
  const { selectedProjectId, selectedProject } = useProject(); const [tab, setTab] = useState<Tab>('cost'); const projectId = selectedProjectId === 'all' ? '' : selectedProjectId;
  const query = useQuery({ queryKey: ['analytics', tab, projectId], enabled: Boolean(projectId), queryFn: async () => { const response = await api.get<CostData | ABCItem[] | SDEItem[] | EOQItem[]>(`/analytics/${tab}`, { projectId }); return response.data; } });
  const tabs: Array<{ id: Tab; label: string }> = [{ id: 'cost', label: 'Cost analysis' }, { id: 'abc', label: 'ABC analysis' }, { id: 'sde', label: 'SDE analysis' }, { id: 'eoq', label: 'EOQ' }];
  return <div className="space-y-6"><div><div className="flex items-center gap-2 text-sky-400"><BarChart3 size={20} /><span className="eyebrow">DECISION SUPPORT</span></div><h1 className="mt-2 text-2xl font-black font-heading text-white">Analytics</h1><p className="mt-1 text-xs text-slate-400">Analyze cost, material criticality, scarcity, and order economics for the active project.</p></div><div className="flex gap-2 overflow-x-auto border-b border-slate-800">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-xs font-bold ${tab === item.id ? 'border-sky-400 text-sky-300' : 'border-transparent text-slate-400 hover:text-white'}`}>{item.label}</button>)}</div>{!projectId && <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/40 p-10 text-center text-sm text-slate-400">Select a project from the workspace scope selector to load analytics.</div>}{projectId && query.isLoading && <State text="Loading analytics..." />}{projectId && query.isError && <State text={query.error instanceof Error ? query.error.message : 'Unable to load analytics.'} error />}{projectId && query.isSuccess && tab === 'cost' && <CostView data={query.data as CostData} projectName={selectedProject?.name} />}{projectId && query.isSuccess && tab === 'abc' && <ABCView data={query.data as ABCItem[]} />}{projectId && query.isSuccess && tab === 'sde' && <SDEView data={query.data as SDEItem[]} />}{projectId && query.isSuccess && tab === 'eoq' && <EOQView data={query.data as EOQItem[]} />}</div>;
}
function CostView({ data, projectName }: { data: CostData; projectName?: string }) { const cards = [['Ordered', (data.summary?.totalOrderedCost ?? 0).toLocaleString()], ['Issued', (data.summary?.totalIssued ?? 0).toLocaleString()], ['Waste cost', (data.summary?.totalWasteCost ?? 0).toLocaleString()], ['Waste rate', `${(Number(data.summary?.wastePercentage) || 0).toFixed(1)}%`]]; return <section className="space-y-4"><p className="text-xs text-slate-400">Project: <span className="text-slate-200">{projectName}</span></p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-white">{value}</p></div>)}</div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 text-sm font-bold text-white">Spend by category</h2><Rows headers={['Category', 'Quantity', 'Cost']} rows={(data.byCategory || []).map((item) => [item.category, String(item.quantity ?? 0), (Number(item.cost) || 0).toLocaleString()])} /></div></section>; }
function ABCView({ data }: { data: ABCItem[] }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><Rows headers={['Material', 'Annual consumption value', 'Share', 'Class']} rows={(data || []).map((item) => [item.materialName, (Number(item.annualConsumptionValue) || 0).toLocaleString(), `${(Number(item.percentage) || 0).toFixed(1)}%`, item.classification])} /></section>; }
function SDEView({ data }: { data: SDEItem[] }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><Rows headers={['Material', 'Scarcity', 'Difficulty', 'Class']} rows={(data || []).map((item) => [item.materialName, item.scarcity, item.difficulty, item.classification])} /></section>; }
function EOQView({ data }: { data: EOQItem[] }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><Rows headers={['Material', 'Annual demand', 'Ordering cost', 'Holding cost', 'EOQ', 'Total cost']} rows={(data || []).map((item) => [item.materialName, String(item.annualDemand ?? 0), (Number(item.orderingCost) || 0).toLocaleString(), (Number(item.holdingCost) || 0).toLocaleString(), (Number(item.eoq) || 0).toFixed(2), (Number(item.totalCost) || 0).toLocaleString()])} /></section>; }
function Rows({ headers, rows }: { headers: string[]; rows: string[][] }) { if (!rows.length) return <p className="py-8 text-center text-sm text-slate-500">No analytics data available.</p>; return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr>{headers.map((header) => <th className="px-4 py-3" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-800/70">{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((cell, cellIndex) => <td className={`px-4 py-4 ${cellIndex === 0 ? 'font-semibold text-white' : 'text-slate-300'}`} key={`${cell}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-xl border p-8 text-center text-sm ${error ? 'border-rose-900/60 bg-rose-950/30 text-rose-300' : 'border-dashed border-slate-700 bg-slate-900/40 text-slate-400'}`}>{text}</div>; }
