import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ShieldCheck, Users as UsersIcon } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../services/api';
import type { User, UserRole } from '../../types';

const roles: UserRole[] = ['admin', 'manager', 'engineer', 'store_keeper', 'viewer'];
async function getUsers() { const response = await api.get<User[]>('/users'); return Array.isArray(response.data) ? response.data : []; }
export function UsersPage() {
  const { user } = useAuth(); const client = useQueryClient(); const [error, setError] = useState<string | null>(null); const users = useQuery({ queryKey: ['users'], queryFn: getUsers });
  const updateRole = useMutation({ mutationFn: ({ id, role }: { id: string; role: UserRole }) => api.patch(`/users/${id}/role`, { role }), onSuccess: () => client.invalidateQueries({ queryKey: ['users'] }), onError: (cause) => setError(cause instanceof Error ? cause.message : 'Unable to update role.') });
  const updateStatus = useMutation({ mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) => api.patch(`/users/${id}/status`, { isActive }), onSuccess: () => client.invalidateQueries({ queryKey: ['users'] }), onError: (cause) => setError(cause instanceof Error ? cause.message : 'Unable to update status.') });
  if (user?.role !== 'admin') return <div className="rounded-xl border border-rose-900/60 bg-rose-950/30 p-6 text-sm text-rose-300">Administrator access is required to manage users.</div>;
  return <div className="space-y-6"><div><div className="flex items-center gap-2 text-amber-500"><UsersIcon size={20} /><span className="eyebrow">ACCESS CONTROL</span></div><h1 className="mt-2 text-2xl font-black font-heading text-white">Users & Roles</h1><p className="mt-1 text-xs text-slate-400">Manage access roles and account status for workspace users.</p></div>{users.isLoading && <State text="Loading users..." />}{users.isError && <State text={users.error instanceof Error ? users.error.message : 'Unable to load users.'} error />}{users.isSuccess && !users.data.length && <State text="No users found." />}{users.data && users.data.length > 0 && <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[700px] text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Joined</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-800/70">{users.data.map((member) => <tr key={member._id}><td className="px-4 py-4"><p className="font-semibold text-white">{member.name}</p><p className="mt-1 text-slate-500">{member.email}</p></td><td className="px-4 py-4"><select value={member.role} onChange={(event) => updateRole.mutate({ id: member._id, role: event.target.value as UserRole })} disabled={member._id === user._id} className="rounded-lg border border-slate-700 bg-slate-950 px-2 py-1.5 text-xs capitalize text-slate-200 disabled:opacity-50">{roles.map((role) => <option key={role} value={role}>{role.replace('_', ' ')}</option>)}</select></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${member.isActive ? 'bg-emerald-500/15 text-emerald-300' : 'bg-slate-700 text-slate-400'}`}>{member.isActive ? 'Active' : 'Inactive'}</span></td><td className="px-4 py-4 text-slate-500">{member.createdAt || '—'}</td><td className="px-4 py-4"><button type="button" disabled={member._id === user._id} onClick={() => updateStatus.mutate({ id: member._id, isActive: !member.isActive })} className="text-xs font-semibold text-slate-400 hover:text-white disabled:opacity-40">{member.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}{error && <p className="text-xs text-rose-300" role="alert">{error}</p>}<div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14} /> User creation is not available because the backend exposes no admin user-create endpoint.</div></div>;
}
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-xl border p-8 text-center text-sm ${error ? 'border-rose-900/60 bg-rose-950/30 text-rose-300' : 'border-dashed border-slate-700 bg-slate-900/40 text-slate-400'}`}>{text}</div>; }
